// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
//
// `prisma.config.ts` disables Prisma's automatic env loading, so we load .env
// ourselves. dotenv alone does NOT expand ${VAR} references — dotenv-expand
// adds that, matching the behavior Next.js and docker-compose already use.
import dotenv from 'dotenv';
import { expand } from 'dotenv-expand';
expand(dotenv.config());

import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Must be the full command — a bare path lets the OS pick a handler,
    // which on Windows opens .ts files in a media player (MPEG Transport Stream).
    seed: 'tsx prisma/seed.ts',
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL'),
  },
});