export const harryPotterData = [
  {
    id: 1,
    name: 'Harry Potter',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Holly, Phoenix Feather',
    spells: [
      { id: 1, name: 'Expelliarmus', type: 'Charm' },
      { id: 2, name: 'Expecto Patronum', type: 'Defensive' },
      { id: 3, name: 'Stupefy', type: 'Charm' },
      { id: 4, name: 'Accio', type: 'Charm' },
    ],
  },
  {
    id: 2,
    name: 'Hermione Granger',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Vine, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Alohomora', type: 'Utility' },
      { id: 2, name: 'Obliviate', type: 'Memory' },
      { id: 3, name: 'Wingardium Leviosa', type: 'Charm' },
      { id: 4, name: 'Reparo', type: 'Utility' },
      { id: 5, name: 'Lumos', type: 'Utility' },
    ],
  },
  {
    id: 3,
    name: 'Draco Malfoy',
    house: 'Slytherin',
    role: 'Student',
    status: 'ON_PROBATION',
    wand: 'Hawthorn, Unicorn Hair',
    spells: [
      { id: 1, name: 'Expelliarmus', type: 'Charm' },
      { id: 2, name: 'Crucio', type: 'Unforgivable' },
    ],
  },
  {
    id: 4,
    name: 'Ron Weasley',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Willow, Unicorn Hair',
    spells: [
      { id: 1, name: 'Wingardium Leviosa', type: 'Charm' },
      { id: 2, name: 'Stupefy', type: 'Charm' },
      { id: 3, name: 'Accio', type: 'Charm' },
    ],
  },
  {
    id: 5,
    name: 'Luna Lovegood',
    house: 'Ravenclaw',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Thestral Tail Hair',
    spells: [
      { id: 1, name: 'Stupefy', type: 'Charm' },
      { id: 2, name: 'Expelliarmus', type: 'Charm' },
      { id: 3, name: 'Patronus', type: 'Defensive' },
    ],
  },
  {
    id: 6,
    name: 'Neville Longbottom',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Cherry, Unicorn Hair',
    spells: [
      { id: 1, name: 'Expelliarmus', type: 'Charm' },
      { id: 2, name: 'Herbivicus', type: 'Utility' },
    ],
  },
  {
    id: 7,
    name: 'Ginny Weasley',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Yew, Unknown Core',
    spells: [
      { id: 1, name: 'Bat Bogey Hex', type: 'Hex' },
      { id: 2, name: 'Stupefy', type: 'Charm' },
      { id: 3, name: 'Reducto', type: 'Charm' },
    ],
  },
  {
    id: 8,
    name: 'Cedric Diggory',
    house: 'Hufflepuff',
    role: 'Student',
    status: 'INACTIVE',
    wand: 'Ash, Unicorn Hair',
    spells: [
      { id: 1, name: 'Accio', type: 'Charm' },
      { id: 2, name: 'Expecto Patronum', type: 'Defensive' },
    ],
  },
  {
    id: 9,
    name: 'Cho Chang',
    house: 'Ravenclaw',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Expelliarmus', type: 'Charm' },
      { id: 2, name: 'Stupefy', type: 'Charm' },
    ],
  },
  {
    id: 10,
    name: 'Pansy Parkinson',
    house: 'Slytherin',
    role: 'Student',
    status: 'ON_PROBATION',
    wand: 'Unknown, Unknown Core',
    spells: [],
  },
  {
    id: 11,
    name: 'Albus Dumbledore',
    house: 'Gryffindor',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Elder Wand, Thestral Tail Hair',
    spells: [
      { id: 1, name: 'Expelliarmus', type: 'Charm' },
      { id: 2, name: 'Lumos Maxima', type: 'Utility' },
      { id: 3, name: 'Avada Kedavra', type: 'Unforgivable' },
      { id: 4, name: 'Fiendfyre', type: 'Dark' },
      { id: 5, name: 'Sectumsempra', type: 'Dark' },
    ],
  },
  {
    id: 12,
    name: 'Severus Snape',
    house: 'Slytherin',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Sectumsempra', type: 'Dark' },
      { id: 2, name: 'Legilimens', type: 'Mind' },
      { id: 3, name: 'Expecto Patronum', type: 'Defensive' },
      { id: 4, name: 'Wingardium Leviosa', type: 'Charm' },
    ],
  },
  {
    id: 13,
    name: 'Minerva McGonagall',
    house: 'Gryffindor',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Fir, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Transfiguration', type: 'Transfiguration' },
      { id: 2, name: 'Piertotum Locomotor', type: 'Charm' },
      { id: 3, name: 'Stupefy', type: 'Charm' },
    ],
  },
  {
    id: 14,
    name: 'Rubeus Hagrid',
    house: 'Gryffindor',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Oak, Unknown Core',
    spells: [{ id: 1, name: 'Wingardium Leviosa', type: 'Charm' }],
  },
  {
    id: 15,
    name: 'Lord Voldemort',
    house: 'Slytherin',
    role: 'Dark Lord',
    status: 'BANNED',
    wand: 'Yew, Phoenix Feather',
    spells: [
      { id: 1, name: 'Avada Kedavra', type: 'Unforgivable' },
      { id: 2, name: 'Crucio', type: 'Unforgivable' },
      { id: 3, name: 'Imperio', type: 'Unforgivable' },
      { id: 4, name: 'Fiendfyre', type: 'Dark' },
      { id: 5, name: 'Legilimens', type: 'Mind' },
    ],
  },
  {
    id: 16,
    name: 'Bellatrix Lestrange',
    house: 'Slytherin',
    role: 'Death Eater',
    status: 'BANNED',
    wand: 'Walnut, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Crucio', type: 'Unforgivable' },
      { id: 2, name: 'Avada Kedavra', type: 'Unforgivable' },
      { id: 3, name: 'Fiendfyre', type: 'Dark' },
    ],
  },
  {
    id: 17,
    name: 'Sirius Black',
    house: 'Gryffindor',
    role: 'Order of the Phoenix',
    status: 'INACTIVE',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Stupefy', type: 'Charm' },
      { id: 2, name: 'Expelliarmus', type: 'Charm' },
    ],
  },
  {
    id: 18,
    name: 'Remus Lupin',
    house: 'Gryffindor',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Cypress, Unicorn Hair',
    spells: [
      { id: 1, name: 'Expecto Patronum', type: 'Defensive' },
      { id: 2, name: 'Riddikulus', type: 'Charm' },
      { id: 3, name: 'Stupefy', type: 'Charm' },
    ],
  },
  {
    id: 19,
    name: 'Dolores Umbridge',
    house: 'Slytherin',
    role: 'Professor',
    status: 'BANNED',
    wand: 'Birch, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Crucio', type: 'Unforgivable' },
      { id: 2, name: 'Incarcerous', type: 'Binding' },
    ],
  },
  {
    id: 20,
    name: 'Fred Weasley',
    house: 'Gryffindor',
    role: 'Student',
    status: 'INACTIVE',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Accio', type: 'Charm' },
      { id: 2, name: 'Bombarda', type: 'Charm' },
    ],
  },
  {
    id: 21,
    name: 'George Weasley',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Accio', type: 'Charm' },
      { id: 2, name: 'Bombarda', type: 'Charm' },
      { id: 3, name: 'Expelliarmus', type: 'Charm' },
    ],
  },
  {
    id: 22,
    name: 'Percy Weasley',
    house: 'Gryffindor',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Stupefy', type: 'Charm' },
      { id: 2, name: 'Lumos', type: 'Utility' },
    ],
  },
  {
    id: 23,
    name: 'Fleur Delacour',
    house: 'Beauxbatons',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Rosewood, Veela Hair',
    spells: [
      { id: 1, name: 'Accio', type: 'Charm' },
      { id: 2, name: 'Immobulus', type: 'Charm' },
      { id: 3, name: 'Expelliarmus', type: 'Charm' },
    ],
  },
  {
    id: 24,
    name: 'Viktor Krum',
    house: 'Durmstrang',
    role: 'Student',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Conjunctivitis Curse', type: 'Curse' },
      { id: 2, name: 'Stupefy', type: 'Charm' },
    ],
  },
  {
    id: 25,
    name: 'Nymphadora Tonks',
    house: 'Hufflepuff',
    role: 'Order of the Phoenix',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Expelliarmus', type: 'Charm' },
      { id: 2, name: 'Stupefy', type: 'Charm' },
      { id: 3, name: 'Protego', type: 'Defensive' },
    ],
  },
  {
    id: 26,
    name: 'Filius Flitwick',
    house: 'Ravenclaw',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Wingardium Leviosa', type: 'Charm' },
      { id: 2, name: 'Piertotum Locomotor', type: 'Charm' },
      { id: 3, name: 'Stupefy', type: 'Charm' },
      { id: 4, name: 'Expelliarmus', type: 'Charm' },
    ],
  },
  {
    id: 27,
    name: 'Pomona Sprout',
    house: 'Hufflepuff',
    role: 'Professor',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Herbivicus', type: 'Utility' },
      { id: 2, name: 'Stupefy', type: 'Charm' },
    ],
  },
  {
    id: 28,
    name: 'Lucius Malfoy',
    house: 'Slytherin',
    role: 'Death Eater',
    status: 'BANNED',
    wand: 'Elm, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Avada Kedavra', type: 'Unforgivable' },
      { id: 2, name: 'Imperio', type: 'Unforgivable' },
      { id: 3, name: 'Expelliarmus', type: 'Charm' },
    ],
  },
  {
    id: 29,
    name: 'Peter Pettigrew',
    house: 'Gryffindor',
    role: 'Death Eater',
    status: 'BANNED',
    wand: 'Chestnut, Dragon Heartstring',
    spells: [
      { id: 1, name: 'Avada Kedavra', type: 'Unforgivable' },
      { id: 2, name: 'Fidelius Charm', type: 'Charm' },
    ],
  },
  {
    id: 30,
    name: 'Alastor Moody',
    house: 'Gryffindor',
    role: 'Order of the Phoenix',
    status: 'IN_GOOD_STANDING',
    wand: 'Unknown, Unknown Core',
    spells: [
      { id: 1, name: 'Stupefy', type: 'Charm' },
      { id: 2, name: 'Expelliarmus', type: 'Charm' },
      { id: 3, name: 'Avada Kedavra', type: 'Unforgivable' },
      { id: 4, name: 'Protego', type: 'Defensive' },
    ],
  },
];
